### ISSUE TITLE
Installing this player on wordpress

### ISSUE THREAD

**Issue by machonatural** [fluid-player/fluid-player#13]
Hi can anyone tell how to proceed the step by step and install this player into my wordpress. I dont know where to place the code.

**Comment by cradonn** [comment]
Hi @machonatural,

We will be releasing improved integration documentation in the coming days and weeks and as part of this it will cover some of the major CMS and blog installs.

**Comment by naftalina** [comment]
Ciao, ci sono novità per l'integrazione del player su Wordpress ???

**Comment by exoclick-florin-tudor** [comment]
We have prepared a wordpress plugin for fluid player, here's the link: https://wordpress.org/plugins/fluid-player/
Easiest way to use it after installing/activating is to add the [fluidplayer] shortcode to any of your pages.

**Comment by machonatural** [comment]
Hi @exoclick-florin-tudor  ive installed according your guide BUT
When i try to put it to work with the code
[fluid-player video=”maconha-e-porra.mp4″ layout=”default”]
I just got the example video. 

2  question

How is the  correct form? and where do  i  put the exoclick vast address?

Tks in advance

Antonio

**Comment by exoclick-florin-tudor** [comment]
Hello @machonatural,
Both the video parameter and the vast file parameters need to be filled with the corresponding publicly accessible resource URLs, a rough example would be the following:
[fluid-player video=”/path/to/foo.mp4″ vast_file=”/path/to/vast.xml”]

**Comment by machonatural** [comment]
Haha  got it now. Quotation trouble...Newbie total.

2017-05-12 5:30 GMT-03:00 exoclick-florin-tudor <notifications@github.com>:

**Comment by seyntjim** [comment]
Same problem here with @machonatural. No idea how to integrate the exoclick ad codes with the player plugin.

**Comment by cradonn** [comment]
Unrelated topics need to be created as new issues.

**Comment by MarinYotovski** [comment]
Hello @machonatural and @seyntjim,

In order to embed Fluid Player in WordPress and display an InStrem ad from Exoclick, here is how the embed code should look like:

`[fluid-player video="http://localhost/wordpress/wp-content/uploads/2016/09/SampleVideo_720x480_1mb.mp4" vast_file="https://syndication.exoclick.com/splash.php?idzone=1111111"]`

I have personally tested the code above and I do see an InStream ad. Please use a real zone id, taken from the Exoclick Admin Panel. Also, use the URL (called VAST Tag) exactly as it is provided by Exoclick (without adding .xml).

If you don't see an ad, this does not necessarily mean that the setup is wrong. There are various reason for not seeing an ad, including:
- InStream ads usually have limits, so an ad is not delivered on each page refresh.
- There may not be a suitable ad to display for the current user at this time.

Nevertheless, you can still check if the setup is correct. After loading the page, open the browser console (i.e. Firebug) and go to the Network tab. Then when clicking on the video player in order to start it, a call to the VAST Tag URL should be performed. If the response contains an empty VAST Tag, this means that the setup is correct, but for some reason there is currently no ad to display, probably due to one of the two reasons I mentioned.

Here is how an empty VAST Tag looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<VAST version="3.0"/>
```

This description is only valid for the WordPress plugin of Fluid Player. For a Fluid Player setup on a standard web page, please follow the player documentation.

Please let us know if you have further questions.

Kind Regards
Marin

**Comment by mubali2003** [comment]
Hi,
 I no have knowledge of this installation.
How and wher i put short code? Allso VATS ads code
Can you explain?
Thank you

**Comment by exoclick-florin-tudor** [comment]
Hello @mubali2003,
I'm passing a sample shortcode that should work if  embedded in any of you pages/posts: 

`[fluid-player video="http://cdn.fluidplayer.com/current/examples/video360.mp4" vast_file="/wp-content/plugins/fluid-player/web/examples/vast.xml"]`

Basically the minimum needed is the actual video file (a FluidPlayer CDN sample in this case) and the vast file URl (used the hosted plugin one). Give it a try and let us know if you encounter any issues.

**Comment by naftalina** [comment]
Scusate me delle impostazioni nel pannelo di Wordpress non sarebbe più semplice, anche per inseire tag VAST , e dimensioni del player

**Comment by felipecs4** [comment]
I got it resolved here.

First you go into the cpanel file manager and it goes
download the vast.xml file at: /wp-content/plugins/fluid-player/web/examples/vast.xml

After that, you will open it in Notepad and search for:
- <VideoClicks>

- <ClickThrough>

<! [CDATA [https://www.fluidplayer.com/]]>

here will be the link of the ad, you will change to the link you want to send the user who clicks the ad, I want to send who click on the ad to google, so I do:
ex:
- <VideoClicks>


- <ClickThrough>

<! [CDATA [https://google.com]]>

after that, you will place the ad video address.
look in the separate code:

- <MediaFiles>


- <MediaFile type = "video / mp4" delivery = "progressive">

<! [CDATA [http://cdn.fluidplayer.com/1.1.0//examples/pre-ad.mp4]]>

here you will enter the link address of the ad video, the same strength as the ad link.

finalized

Now save the changes of this here .xml and upload again in the site, by cpanel, wordpress does not let rise.



now use the .xml file address in vast_file

Example:
[fluid-player video = "http://cdn.fluidplayer.com/current/examples/video360.mp4" vast_file = "/ wp-content / plugins / fluid-player / web / examples / vast.xml"]

Remember: in the xml file has what is described: ad address and video address.

I'm Brazilian and I made this tutorial by google translator, forgive any mistake

**Comment by WesleyCarnicl** [comment]
can it work with youtube
