### ISSUE TITLE
Problem with download button - bag

### ISSUE THREAD

**Issue by crnidario** [fluid-player/fluid-player#255]
Hello,
I noticed that from desktop in some browsers (Opera, Chrome, Firefox ) when I click on download button it doesn’t open windows downloading bar (to save on a computer), instead of that directly opens mp4 url in new tab and playing video again. 
Before fluid-player I used the kt-player and that option is worked properly.

**Comment by cian-exads** [comment]
Hi @crnidario, can you link a page to see this happen? We'll look into this issue and get a fix in place.

**Comment by Addvilz** [comment]
This is a somewhat expected behavior and depends entirely on the server where the video is served from.

By default, browsers will inline display supported videos. To force browser to download the video as file you need to use `Content-Disposition` header on the video serving side.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
