### ISSUE TITLE
2.4.3 css adText position

### ISSUE THREAD

**Issue by det66** [fluid-player/fluid-player#274]
Where is the size and position of adText defined in the CSS?

**Comment by cian-exads** [comment]
Hi @det66, the position of adText is based on the set parameters which is why the css is found in the javascript where these elements are created. You can find the specific adText css being added at this point - https://github.com/fluid-player/fluid-player/blob/a062cf46abbda52ab7d1a9c94c4a732a9ec47ed9/fluidplayer.js#L1888-L1914

**Comment by det66** [comment]
Ok, I'm no javascript expert.
What do I have to change where to have the adText in the top left corner (2px from top and 2px from left)
with a fontsize of 10px?

**Comment by cian-exads** [comment]
You can set these values in using the **!important** parameter to overwrite the css set during initialisation. This means you won't have to change anything in the Fluid Player files. Something like what's shown below should accomplish what you're hoping for.

```
<style>
  .fluid_ad_playing {
    top: 2px !important;
    left: 2px !important;
    font-size: 10px !important;
  }
</style>

**Comment by det66** [comment]
working perfect.
Thank you

**Comment by cian-exads** [comment]
@det66 happy to help!
