### ISSUE TITLE
preload="none" not working

### ISSUE THREAD

**Issue by phansheng89** [fluid-player/fluid-player#360]
Hi,

Whether I set preload="none" or preload="auto", the video is reloaded before user press play button, on Chrome.

I test this preload on videojs and it works accordingly so  I don't think it's browser issue.

Thanks.

**Comment by Lestadt** [comment]
Hi, I'm not an expert, I'm just a simple user, I'll tell you what works for me. You just have to change from preload = "none" to preload: false, as simple as that, I hope it works for you.
![preload-Captura](https://user-images.githubusercontent.com/52806949/64374809-8dd39600-cff2-11e9-9548-7a06108b33e3.JPG)

**Comment by hitmanex** [comment]
this doesn't work. It completely ignores preload

**Comment by Lestadt** [comment]
Can you paste here the complete code you are using for the player?

**Comment by hitmanex** [comment]
I'm quite an advanced user and have a wrapper for the player..

but my config is as follows

`var myFP=fluidPlayer('"+rdid+"',{layoutControls:{fillToContainer:false,primaryColor:\"#D3D3D3\",posterImage:false,autoPlay:false,preload:false,playButtonShowing:true,playPauseAnimation:true,mute:false,logo:{imageUrl:null,position:'top left',clickUrl:null,opacity:1,mouseOverImageUrl:null,imageMargin:'2px',hideWithControls:false,showOverAds:false},htmlOnPauseBlock:{html:null,height:null,width:null},allowDownload:false,allowTheatre:false,playbackRateEnabled:false,controlBar:{autoHide:true,autoHideTimeout:3,animated:true},},vastOptions:{}});`

It preloads .mp4 files on both chrome and firefox (seen on the network tab)

**Comment by Lestadt** [comment]
Your code is very similar to mine, however, mine works. I was stuck for a long time and tried several configurations, in my case what solved this problem was what I published, I don't know why in your case it doesn't work. It doesn't work ... something I can ask you if you use something to minify or measure the .js files, if so, add an exception so that fluidplayer.min.js is not minified and try again ... luck.

**Comment by hitmanex** [comment]
yes I minify the files and its behind cloudflare so it gets auto minified. But all the other configurations work so why is it preloading. Also there's another recent thread about preloading under issues here.

where do you have preload:false in the very beginning? maybe it's come combination glitch with another option

**Comment by Lestadt** [comment]
Well, that is the problem, the preload does not work because the file is minimized. I mentioned that your code is very similar to mine and mine works, but mine is not minimized. When I started using this player, it was minimized and I had to create an exception so that it is not minimized, I don't remember what problem caused me on that occasion. In the small capture that I publish, you will see where the preload is preload: false, it is right at the beginning. I currently don't use Cloudflare and I don't know if you can create an exception for the fluidplayer.min.js file, it would be nice if you tried, I'm almost sure why the preload doesn't work for you.

**Comment by hitmanex** [comment]
alright i figured the issue out. the issue is within the player itself.

`        videoPlayerTag.setAttribute('preload', this.displayOptions.layoutControls.preload);
`
assumes `<video id=xxx preload="false">` (or true, or auto).

whereas the correct values are auto, metadata, or none. 

So to fix it you simply do `preload:'none' `for layoutControls, even tho it's not documented properly..

**Comment by Lestadt** [comment]
> preload:'none'



> alright i figured the issue out. the issue is within the player itself.
> 
> ` videoPlayerTag.setAttribute('preload', this.displayOptions.layoutControls.preload);`
> assumes `<video id=xxx preload="false">` (or true, or auto).
> 
> whereas the correct values are auto, metadata, or none.
> 
> So to fix it you simply do `preload:'none' `for layoutControls, even tho it's not documented properly..

I wanted to help you and it turns out that you have helped me, although my code worked as I wanted I made the small change you suggested and everything is a little faster, it works better, I have saved some milliseconds, thank you friend, good suggestion.

**Comment by redrabbit85** [comment]
Mmm, sorry. How to fix this? I still don't understand.
I put in to my config this
preload:'none'
It doesn't matter.
It's easy config
`
	fluidPlayer('video-id',
	{
		layoutControls: {
			posterImage: '/images/large/bbb.jpg',
			preload:'none',
			autoPlay: false,
		},
		vastOptions: {
			//Zzzzzzz
		}
	}
);
`
OR THIS
`
   var myFP = fluidPlayer(
        'video-id',
        {
            layoutControls: {
		fillToContainer: false,
		primaryColor: false,
		preload:'none',
		posterImage: false,
		autoPlay: false,
		playButtonShowing: true,
		playPauseAnimation: true,
		mute: false,
		logo: {
			imageUrl: null,
			position: 'top left',
			clickUrl: null,
			opacity: 1,
			mouseOverImageUrl: null,
			imageMargin: '2px',
			hideWithControls: false,
			showOverAds: false
		},
		htmlOnPauseBlock: {
			html: null,
			height: null,
			width: null
		},
		allowDownload: false,
		allowTheatre: true,
		playbackRateEnabled: false,
		controlBar: {
			autoHide: false,
			autoHideTimeout: 3,
			animated: true
		},
            },
            vastOptions: {
                // 
            }
        }
    );
`

**Comment by hitmanex** [comment]
either show me an example page or confirm in developer tools in your browser that 
![image](https://user-images.githubusercontent.com/34111698/67823110-3143a300-fa98-11e9-9305-9bc96ee3606d.png)

the preload=none attribute is actually there

**Comment by redrabbit85** [comment]
![image](https://user-images.githubusercontent.com/3734535/67884926-b80b8500-fb57-11e9-9592-20ea4ada9a63.png)
![ScreenCaptureProject2](https://user-images.githubusercontent.com/3734535/67885780-3caad300-fb59-11e9-9f14-2b84d47b625c.gif)
**Loading *.ts**
Code
![image](https://user-images.githubusercontent.com/3734535/67886572-bbecd680-fb5a-11e9-8dbc-170dea3d2b84.png)

**Comment by Lestadt** [comment]
Hello @redrabbit85, the site you sent as an example does not use Fluid Player, that site uses VideoJs, possibly the parameters are not the same, otherwise, check the url you sent and you are not using any parameters for Preload, look at Gtmetrix and part of the video is loading just by opening the url .. I am not sure if you want to switch to VideoJs, or if you want to implement the Preload to Fluid Player, it seems that it is already implemented, I don't know if you want to confirm if it worked for you or not, yes would you be a little clearer at least I could give you some guidance .. Preload is working for you or not?

**Comment by redrabbit85** [comment]
Thanks for reply. I don't want load *.ts file when page loading. Many web bot load my files and I don't want them load traffic. I want load *.ts files when user click on play button. 
I know it another script.
Can you help me?

**Comment by Lestadt** [comment]
Can you send one of your url that has Fluid Player loaded and working? .. If you want you can create a sample page just for testing, just put the Fluid Player script with the current configuration you use, if that is possible, post it here. I'm a little busy, but I'll take the time.

**Comment by redrabbit85** [comment]
Hm, I don't know how to send text in your PM. My Telegram is https://t.me/redrabbit85
I send you worked site.

**Comment by hitmanex** [comment]
as lestadt mentioned, the site you linked is videojs..

your developer tools parameter looks correct, however i don't use m3u8 (HLS) and not sure how preload affects m3u8 files..

**Comment by redrabbit85** [comment]
I changed source to mp4 and preload "none" is working. 
But I still don't know why HLS is loading.
I trying use on play api. I changed source scr via jquery and this worked, but video didn't loading.

**Comment by hitmanex** [comment]
I don't use HLS..It might preload by default based on web browser standards and the video tag..i have no idea

**Comment by Addvilz** [comment]
preload seems to be working just fine. What pays to remember is that preload is a hint argument - browsers and crawlers CAN ignore it entirely.

**Comment by kemalimyapmaz** [comment]
<html>
<body>

my settings are exactly like this and preload works.


<script>var r = document.createElement("meta");r.name = "referrer", r.content = "never", document.getElementsByTagName("head")[0].appendChild(r);
--
  | var myFP = fluidPlayer(
  | 'html5',
  | {
  | width:"100%",
  | height:"100%",
  | fillToContainer: true,
  | layoutControls: {
videoUrl: '[https://www.pornosauvage.com/video/41060-il-baise-sa-cousine-bareback-et-ejacule-sur-son-cul/](https://www.pornosauvage.com/video/41060-il-baise-sa-cousine-bareback-et-ejacule-sur-son-cul/)',
preload:none,
  | posterImage: 'https://www.pornosauvage.com/uploads/preview/44089/fullscreen.jpg',
  | keyboardControl: true,
  | allowTheatre: false,
  | preload: 'none',
  | controlBar: {
  | autoHide: true,
  | autoHideTimeout: 3,
  | animated: false
  | }},
  | }
  | );</script>


</body>
</html>
