### ISSUE TITLE
Chrome Warning "The provided value 'middle' is not a valid enum value of type AlignSetting"

### ISSUE THREAD

**Issue by phansheng89** [fluid-player/fluid-player#449]
**Describe the bug**
When using VTT subtitle, Chrome show warning "The provided value 'middle' is not a valid enum value of type AlignSetting." vendors~vttjs.min.js:1

1. Go to Chrome Inspect
 
 - OS: Chrome on Win 10

Thank you.

**Comment by Addvilz** [comment]
@phansheng89 can you provide the subtitles file, please?

**Comment by phansheng89** [comment]
[2014.zip](https://github.com/fluid-player/fluid-player/files/4662166/2014.zip)
Please see attached file. Thanks.

**Comment by Addvilz** [comment]
This is caused by mozilla/vtt.js#368 which has not been fixed.

There is a fix in a fork of Mozilla vtt.js - videojs/vtt.js#32 - if you are interested in fixing this, you could submit a pull to mozilla/vtt.js with backport from videojs/vtt.js - we could bump the version then.

Otherwise, this is on hold while they fix it.

**Comment by Addvilz** [comment]
We might be able to switch to videojs/vtt.js from Mozilla. This does however require some investigation into API compatibility.

**Comment by Addvilz** [comment]
This should now be fixed with the latest release.
