### ISSUE TITLE
Create 'responsive' container

### ISSUE THREAD

**Issue by doublex** [fluid-player/fluid-player#461]
The property `fillToContainer` should create a responsive container:
`width` should be 100%
`height` should be the correct aspect ratio (according to  `<video width=... height=....>`)

This example shows the effect (resize the browser window):
http://doppelbauer.name/fluid-responsive.html

**Comment by Addvilz** [comment]
After reviewing the issue I am not entirely sure what the issue here is. When `fillToContainer` is set, the video and it's container are 100% height and 100% width (as they are supposed to be). I initially thought that resizing the container does not resize the video, but that is not the case - you can see a test case for that on branch `responsive-test-case`.

Can you provide more details as to what the actual issue is?

**Comment by doublex** [comment]
The `responsive-test-case` wraps a `display: inline-block` container. Which may work for quite a few scenarios (but in mine).
Is there a chance to add a flexible container (`display: block; width: 100%; height:*aspect-ratio`) in the core?
https://www.w3schools.com/howto/howto_css_aspect_ratio.asp

Which should be quite simple to implement.

**Comment by Addvilz** [comment]
This is a case you need to handle in the container as part of your website - we can't assume or even know what aspect ratio each player will have, what video content they can have and similar, 16:9, 4:3, 16:10, etc etc. This is why the wrapper container in the core is 100% height and width - so you can control the aspect however you want just by wrapping the player and it's container in a custom container that fits your need.

**Comment by doublex** [comment]
What about extending the configuration possibilities, e.g. explicit setting of the aspect ratio:
````
fillToContainer:  16.0 / 9.0,
````

**Comment by Addvilz** [comment]
I am sorry but doing that would introduce more issues than it would solve - how about the cases where parent container can not contain one of the aspects of the player? For example, if the height of the parent container is less than the player aspect?

As I mentioned, you can wrap the player and handle aspect that way. You can even use the same technique I used in the demo.

**Comment by doublex** [comment]
Dear Matīss,

Is your decision final? 
My biggest issue: The whole player behaves `display: inline-block` (which of course is the default of `video`-elements but unusual for html5-players).

A solution would be quite simple, e.g.:
````
layoutControls: {
    fillToContainer: 16.0/9.0,
}
````

And this patch:

````
*** src/fluidplayer.js.old      2020-06-23 16:38:43.953183214 +0200
--- src/fluidplayer.js  2020-06-23 16:51:46.618564690 +0200
*************** const fluidPlayerClass = function () {
*** 1925,1931 ****
              : 'fluid_video_wrapper';
  
          //Assign the height/width dimensions to the wrapper
!         if (self.displayOptions.layoutControls.fillToContainer) {
              wrapper.style.width = '100%';
              wrapper.style.height = '100%';
          } else {
--- 1925,1944 ----
              : 'fluid_video_wrapper';
  
          //Assign the height/width dimensions to the wrapper
!         const fillToContainer = self.displayOptions.layoutControls.fillToContainer;
!         if( typeof(fillToContainer) == 'number' ) {
!             //Responsive wrapper: width=100%,height=aspect-ratio according to fillToContainer
!             const aspectRatio = document.createElement('div');
!             aspectRatio.style.paddingTop = (100.0 / fillToContainer) + '%';
!             wrapper.appendChild(aspectRatio);
!             wrapper.style.display = 'block';
!             wrapper.style.width = '100%';
!             self.domRef.player.style.position = 'absolute';
!             self.domRef.player.style.top = 0;
!             self.domRef.player.style.right = 0;
!             self.domRef.player.style.bottom = 0;
!             self.domRef.player.style.left = 0;
!         } else if (fillToContainer) {
              wrapper.style.width = '100%';
              wrapper.style.height = '100%';
          } else {
````

**Comment by Addvilz** [comment]
Yes, sorry, because a valid and fairly simple workaround exists for what you want to achieve, and this really feels like a edge case.

You can use the above code or the css-only version from the test I referenced before, so for me it does not make any sense to implement this in the player itself.

**Comment by Luppakorva** [comment]
This is indeed a huge problem.

There's no proper way to make this player responsive nor maintaining the aspect ratio without it adding huge paddings to top and bottom. 

Please provide a working simple solution for this or proper examples, I can see you have refused to offer a solution for this and have just refferred to css without offering solution.

Just trying to be helpful, I am sure many are turned off from flowplayer due to it being so horrible when it comes to responsive designs / mobile layouts, it just does not play ball at all.

**Comment by Addvilz** [comment]
@Luppakorva the player already is responsive, and has been for years, and you are in full control over the aspect ratio of the player element, as you would be with any other HTML component. What is the issue exactly?

**Comment by Luppakorva** [comment]
@Addvilz thanks for getting back to me about this. If you do change the landscape to portrait mode, the player will not scale correctly, that's not however the biggest issue.

I personally cannot get it to play ball with the aspect ratio, with padding top the video will leave padding on top, yet the video itself is below that no matter what I try csswise.

On mobiles in portrait mode the video's background's height gets insane (Safari and Chrome at least on iOS), even when video is 16:9, this results the video unit height to be insane (example: 450x1270). See: https://imgur.com/a/A11tZ6k

This on fillToContainer true.  If I force the wrapping div height to  500px for example, this is not respected, the controls will be hidden and overlapping the containing div.

If I remove the fillToContainer true or make it false, I can get the result you have on front page https://www.fluidplayer.com/) with width:100% on mobile. Mimicking how you have set it up. This does not scale however, if it's switched from portrait to landscape / viceversa, video width is fixed (I guess calculated and set on load)

With desktops: as I have two column layout, fill to container in turn does not respect the column div's width on larger screens but instead again overlaps, this time the right column (video being in left column). Video takes whole 100% of the full page's width.

Behaviour seems to change quite a lot between different browsers.

I love it what you guys have done here but these issues make it impossible for me to use it in production.

**Comment by Luppakorva** [comment]
@Addvilz so no action taken then? Leaving it broken?

**Comment by Addvilz** [comment]
@Luppakorva what you described sounds like an issue with the styling of your website, not the player itself - any chance you are using some kind of front-end framework and there is inherited styling affecting the video element and other player elements? For example, the screenshot you provided from mobile - I have seen this before and it was due to positioning of the video element forced by a front-end framework. Please check the effective CSS in your browser to eliminate this.

Are you able to consistently reproduce this behavior in a clean-room environment? Are you able to reproduce this with our tests? If so, please provide a way to reproduce these issues, and I may look into it when time allows, or if it is indeed reproducible - you can also submit a pull request with a fix.

Unrelated to above, please consider a change of tone in your next comments. This is a free and open-source software, provided to you, again, for free. Consider that answering you might not always be our top priority above everything. If for that you feel like you should consider alternative projects to this - you are free to do so. This being an open source project, you are also free to fork and provide fixes for the issues you encounter.

**Comment by Luppakorva** [comment]
@Addvilz 

I'll test, thanks for the reply again. However I cannot seem to find anything on css causing this. I can't find a test neither which is online anymore, there seems to have been "responsive" branch for testing it, but it's deleted.  I can only produce it on Safari on mobile, Chrome etc are fine. I just can't find the cause but I'll keep looking.

Regarding the rest. I'm bit puzzled by your answer about my "tone"? 

My goal is to give you direct feedback, I believe my messages have been friendly and to the point. I'm thanking you for your reply, try to explain the issue to my best ability and as it went ignored, simply said asked is it going to get any attention since I am looking this for production project. If you felt it was somehow an attack towards you or an aggressive / lecturing stance, my apologies, did not mean it in  such ways as all. Perhaps if you re-read you notice that as well, I understand text sometimes shows things and stance in completely wrong light. 

Also you being also linked with exoclick and heavily promoted by them does make me believe you'd want direct feedback where things are not working as supposed to, however if you just ignore an reply, yes. I will ask do you do so for a reason or not, but again point was not meant to critize but just to ask since I'm again, waiting for the reply for the production environment :).

**Comment by Addvilz** [comment]
@Luppakorva the test case is part of the source tree (I merged it) and is available here in file `test/html/vod_reponsive.tpl.html`. You should try to reproduce the issue with no external CSS in a clean and empty page, and try to see if there are any extra CSS rules applied to the video element in developer tools of your browser.

About the other thing - your previous comments are quite aggressive - intentionally so or not. Your feedback is welcome, and we appreciate it, and would never ignore what our users have to say about the project. However, the time we have to work on this is limited, and I ask you to be considerate about that - for this, and open source projects as a whole. It could take days, often weeks to get to answer to each individual request, if at all, simply because there is only so much time in a day, and we might have other priorities set that we have might or might not have control over - as illustrated by me responding to you on a holiday, at 9PM. 

If this issue is critical for you, you are always welcome to invest some time in fixing it, both for this project, and other open source software out there - it will serve only to foster open source and strengthen the community as a whole.

Thanks.

**Comment by Luppakorva** [comment]
@Addvilz I really fail to see how you find them aggressive :). Sorry if you do so, not my intention at all. But thank you for the help!
