### ISSUE TITLE
Add dist directory

### ISSUE THREAD

**Issue by sunxiang520** [fluid-player/fluid-player#463]
I want to use jsdelivr cdn,But there is no compiled code,Hope to add dist directory.
https://www.jsdelivr.com/package/npm/fluid-player

**Comment by Addvilz** [comment]
Any particular reason you do not want to use Fluid Player CDN?

**Comment by sunxiang520** [comment]
1. Jsdelivr cdn can accelerate globally,Fluid Player CDN can not accelerate globally.
2. Jsdelivr cdn own large user base
3. Popular js libraries basically support the dist directory,such as jquery,hls.js,vue.js

*  [jquery](https://www.jsdelivr.com/package/npm/jquery)
*  [hls.js](https://www.jsdelivr.com/package/npm/hls.js)
* [vue.js](https://www.jsdelivr.com/package/npm/vue)

**Comment by Addvilz** [comment]
> Jsdelivr cdn can accelerate globally,Fluid Player CDN can not accelerate globally.
I am not sure how you arrived at such conclusion. Can you elaborate? 

> Jsdelivr cdn own large user base
> Popular js libraries basically support the dist directory,such as jquery,hls.js,vue.js

Many libraries do many different things for equally many different reasons and to support wide variety of use cases. In the case of Fluid Player creating a single build file is *not currently possible* because Fluid Player is using opportunistic code splitting (webpack chunking specifically) and loads several JS modules on-demand. 

What it means is you *can not* just create a `dist` and publish it and have it work out of the box everywhere. The whole code splitting function was implemented to minimize the grand total runtime code size - whenever you load Fluid Player from Fluid Player CDN it will aim to load vendor dependencies only when necessary - for example, hls.js will only be loaded IF you have at least one HLS source embedded. Same goes with DASH, Panolens and others. In fact, future releases will use the same approach to split off some heavier parts of the Fluid Player code too. This works when Fluid Player is bundled using Webpack, on CDN and all other bundlers that support code splitting based on async require.

This opportunistic loading has cost - it is necessary to know from where to load the vendor dependencies. Our current CDN distributions have the path bundled during build time as opposed to the old approach of determining that during runtime which was buggy and didn't always work.

**Comment by Addvilz** [comment]
No feedback. Closing.
