### ISSUE TITLE
The player can't reproduce VPAID video 

### ISSUE THREAD

**Issue by ivan-ruizrosello** [fluid-player/fluid-player#467]
The player can't reproduce VPAID video. 

**To Reproduce**
Click the browser to play.

**Expected behavior**
Reproduce VPAID video.

**Screenshots or Links**
![fluidplayererror](https://user-images.githubusercontent.com/11944297/84270668-52d73380-ab2b-11ea-83ae-446b8ce5db1d.png)

```
class MyVideo extends React.Component {
  constructor(props) {
    super(props);
    this.self = React.createRef();
    this.player = null;
  }

  render() {
    return (
      <video ref={this.self}>
        <source
          src="https://cdn.fluidplayer.com/videos/valerian-1080p.mkv"
          data-fluid-hd
          title="1080p"
          type="video/mp4"
        />
      </video>
    );
  }

  componentDidMount() {
    this.player = fluidPlayer(
      this.self.current,
      {
        vastOptions: {
          allowVPAID: true,
          adList: [
            {
              roll: 'preRoll',
              vastTag: 'https://www8.smartadserver.com/video/vpaid?siteid=346437&pgid=1247692&fmtid=89428&ab=1&tgt=&ps=1&pb=0',
            },
          ],
        },
      },
    );
  }

  componentWillUnmount() {
    if (this.player) {
      this.player.destroy();
    }
  }
}

ReactDOM.render(<MyVideo />, document.getElementById('root'));

```

VPAID .xml file/response: 

```
<VAST version="2.0">
<Ad>
<InLine>
<AdSystem version="v1">SMART Adserver</AdSystem>
<AdTitle>SMART AdServer VPAID AdPlayer</AdTitle>
<Impression event="impression_smart">
<![CDATA[ https://creatives.sascdn.com/shim.gif ]]>
</Impression>
<Creatives>
<Creative>
<Linear>
<Duration>00:00:30</Duration>
<AdParameters>
<![CDATA[ { "siteid" : "346437", "pgid" : "1247692", "fmtid" : "89428", "ab" : "1", "tgt" : "", "ps" : "1", "pb" : "0", "nwid" : 3697, "domain" : "www8.smartadserver.com" } ]]>
</AdParameters>
<MediaFiles>
<MediaFile delivery="progressive" type="application/javascript" width="480" height="640" apiFramework="VPAID">
<![CDATA[ https://ced-ns.sascdn.com/diff/video/current/libs/js/vpaid-plugin.js ]]>
</MediaFile>
</MediaFiles>
</Linear>
</Creative>
</Creatives>
</InLine>
</Ad>
</VAST>

```

Desktop: 
 - OS: Linux
 - Browser Chrome, Firefox

Mobile:
 - Device: Redmi Note 7
 - Browser  Chrome

**Affected version**
 v3.0.1

**Comment by Addvilz** [comment]
Hello!

Apologies, but this ticket has been closed because there is no actionable way to identify what the actual issue is.

The initial ticket description fails to provide details required to identify the problem, such as error output, request logs, environment and browser details, and other details that could aid and allow in identifying the problem you are facing.

Before submitting a new ticket, please make sure that the problem you are facing is related to this software and is not a result of a misconfiguration or third party code - including your usage of this software. 

As a general rule, we are unable to help with user-specific implementation details, and we are not able to debug user implementations, such as websites, plugins, scripts, etc..

**You are required to take the minimum steps necessary to identify the issue, such as debugging the software, your specific configuration, the requests made, the responses returned by any external services.**

You are required to submit enough details about the problem so that we would be able to reproduce and verify the problem.

Make sure to fill out any issue templates as provided by the issue tracker when such templates are present.

This is an automatic response. Please, do not reopen or re-create this ticket without addressing the requirements and problems outlined above.
