### ISSUE TITLE
Vast wrapper: [Error] (101): Failed to load Vast [Error] (900): Failed to load Vast

### ISSUE THREAD

**Issue by fedeveloperi81** [fluid-player/fluid-player#480]
**Describe the bug**
Failed to play VAST from Wrapper.
In console:
[Error] (101): Failed to load Vast
[Error] (900): Failed to load Vast

**To Reproduce**
1. In vastOption add vastTag to vast.xml with wrapper https://github.com/InteractiveAdvertisingBureau/VAST_Samples/blob/master/VAST%203.0%20Samples/Wrapper_Tag-test.xml
2. Click play button

**Expected behavior**
Vast from wrapper loads

**Affected version**
v2.4.4 and v3.0.3

**Comment by Addvilz** [comment]
Please provide the exact configuration you are using - second argument to the `fluidPlayer` function.

**Comment by fedeveloperi81** [comment]
player = fluidPlayer("my-player-id",
		{
			vastOptions: {
				allowVPAID: true,
				adList: [{
						roll: 'preRoll',
						vastTag: 'wrapper_test.xml',
					}],
				maxAllowedVastTagRedirects: 4,
			}
		}
	);

**Comment by Addvilz** [comment]
Couple of things here.

Both `wrapper_test.xml` and `VASTAdTagURI` needs to be hosted somewhere local or on a proper web server. https://raw.githubusercontent.com serves content as `text/plain` and Fluid Player will not parse plaintext content as XML. The server needs to send correct XML content type.

That considered, this particular example will not work regardless because Fluid Player currently does not support Companion ads. The first creative in `Inline_Companion_Tag-test.xml` is a companion ad. Fluid Player currently supports only 1 creative served, and it needs to be either linear or non-linear creative - since the first one is a companion ad, and second is the actual creative, it will not work. If you modify the `Inline_Companion_Tag-test.xml` to remove the companion creative, it all works perfectly fine.

If companion support is something that you explicitly require, please open a feature request for that. Thanks!

**Comment by fedeveloperi81** [comment]
We've made more tests and found that fluid won't handle wrapper without <Creatives> section fe
Working example
`
<VAST version="3.0">
    <Ad id="602833">
        <Wrapper>
            <AdSystem>Telemetry</AdSystem>
            <VASTAdTagURI>/vast.xml</VASTAdTagURI>
			<Creatives>
				<Creative></Creative>
			</Creatives>
        </Wrapper>
    </Ad>
</VAST>
`
Not working example
```
<VAST version="3.0">
    <Ad id="602833">
        <Wrapper>
            <AdSystem>Telemetry</AdSystem>
            <VASTAdTagURI>/vast.xml</VASTAdTagURI>
            <Creatives></Creatives>
        </Wrapper>
    </Ad>
</VAST>
```

**Comment by Addvilz** [comment]
I have created #482 to investigate that, I do not recall how this works in context of VAST 3.0 and 4.0, so I need to investigate.
