### ISSUE TITLE
Need support for Ad XML

### ISSUE THREAD

**Issue by agammathur** [fluid-player/fluid-player#484]
**Current Issue**
At present, if we want to show Ad using an Ad XML, then we have to first host it and then provide the Ad Tag to fluid player in 'vastTag' field of 'adList' object. This increase the complexity and cost to use an Ad XML to show Ad to the user using the fluid player.

**Proposed Solution**
Fluid player should have a support to accept both an Ad XML or Ad Tag to show Ads to the user, just like many other players support like VideoJS etc. If needed, we can create a new field 'vastXml' to accept Ad XML just like we use 'vastTag' to accept Ad tag.

**Comment by Addvilz** [comment]
Sorry, I do not follow. What do you mean by "Ad tag"? You want to provide the VAST XML as string without providing it as a URL?

**Comment by agammathur** [comment]
> Sorry, I do not follow. What do you mean by "Ad tag"? You want to provide the VAST XML as string without providing it as a URL?

Yes, by Ad XML support, I mean the player should have capabilities to accept VAST XML directly as a string.

**Comment by Addvilz** [comment]
Sorry, but this is not something we will change. VAST xml is generally dynamically generated by advertising networks. If you want to use static XML, you can as well store it along with other static assets you have for the site you host the player on. 

If you absolutely need to provide static VAST XML - encode the XML content as `data:` URI and provide it to the player instead of  URL in `vastTag` property.

**Comment by agammathur** [comment]
> Sorry, but this is not something we will change. VAST xml is generally dynamically generated by advertising networks. If you want to use static XML, you can as well store it along with other static assets you have for the site you host the player on.
> 
> If you absolutely need to provide static VAST XML - encode the XML content as `data:` URI and provide it to the player instead of URL in `vastTag` property.

I agree, VAST XML is dynamically generated by Ad networks. But, some Ad networks provide this dynamically generated Ad XML directly as a response rather than a Ad Tag ( URL to this dynamically generated VAST). In these cases to use the fluid player, we will have to first host this VAST XML and then, provide its URL to the fluid player in 'vastTag' field. This hosting increases the latency and cost, which can be reduced, if fluid player has an option to even accept this VAST XML directly as a string.

**Comment by Addvilz** [comment]
> some Ad networks provide this dynamically generated Ad XML directly as a response rather than a Ad Tag 

Sorry? Provide how - as response to what?

**Comment by agammathur** [comment]
> > some Ad networks provide this dynamically generated Ad XML directly as a response rather than a Ad Tag
> 
> Sorry? Provide how - as response to what?

As response to there API calls during S2S ( server to server ) integration. In such cases we send the inventory details to an Ad exchange and it returns a winning bid. This bid can have either the VAST XML or a URL which points to the actual VAST XML. If it's a URL then there is a provision in fluid player to accept it but if it's an actual VAST XML then presently we have to host it and then provide its URL to the fluid player.

**Comment by Addvilz** [comment]
This seems like an edge case, I have never heard about exchanges serving VAST as a S2S response. In this particular case your only way to deal with this is to encode the VAST XML as `data:` URL and pass it to the configuration as I mentioned before.

Here's an example. The Base64 encoded string contains empty VAST tag for demonstration purposes and to keep the example readable. You can read more about `data:` URL scheme here - https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs. Be aware that it does come with some limitations, ex 65k char max limit on the payload size - it should normally not be an issue however.

```js
var instance = fluidPlayer(videoTag, {
    vastOptions: {
        allowVPAID: true,
        adList: [
            {
                roll: 'preRoll',
                vastTag: 'data:text/xml;charset=utf-8;base64,PFZBU1Q+PC9WQVNUPg=='
            },
        ]
    }
});
```

All that being said, I do suggest you to seek alternatives to this approach, and perhaps use a "proxy" script/app to serve VAST from a single URL. For example, instead of loading the VAST on page load where the player is located (S2S call), you could extract the S2S code to a separate URL e.g. `https://example.com/myvast/` - and use that in `vastTag`. Then, whenever a request is made against `/myvast/` either serve the response VAST XML or issue a HTTP redirect to the VAST URL returned by the S2S call. Otherwise your main site is completely at the mercy of the ad exchange in terms of latency, load times and stability.
