### ISSUE TITLE
VR Button issue/Bug

### ISSUE THREAD

**Issue by astarace** [fluid-player/fluid-player#491]
The VR button can appear on non-VR videos, but has no effect when pressed.

This should be either removed, or activate a stereoscopic effect like the one used by Youtube.

This can be observed on many sites using fluidplayer 3.

**Comment by Addvilz** [comment]
Please provide details about what browser you are using. I do not see a VR button in any tests we have with either Chrome or Firefox.

**Comment by Addvilz** [comment]
Hello!

Apologies, but this ticket has been closed because there is no actionable way to identify what the actual issue is.

The initial ticket description fails to provide details required to identify the problem, such as error output, request logs, environment and browser details, and other details that could aid and allow in identifying the problem you are facing.

Before submitting a new ticket, please make sure that the problem you are facing is related to this software and is not a result of a misconfiguration or third party code - including your usage of this software. 

As a general rule, we are unable to help with user-specific implementation details, and we are not able to debug user implementations, such as websites, plugins, scripts, etc..

**You are required to take the minimum steps necessary to identify the issue, such as debugging the software, your specific configuration, the requests made, the responses returned by any external services.**

You are required to submit enough details about the problem so that we would be able to reproduce and verify the problem.

Make sure to fill out any issue templates as provided by the issue tracker when such templates are present.

This is an automatic response. Please, do not reopen or re-create this ticket without addressing the requirements and problems outlined above.
