### ISSUE TITLE
Midroll & postroll on mobile not working 

### ISSUE THREAD

**Issue by Daisum** [fluid-player/fluid-player#500]
Vast midroll and postroll on not playing on mobile chrome browser. 

Using latest fluidplayer version v3.0.4
Using exoclick VAST

Using 50% video length for midroll. 

**To Reproduce**
1. Load player with 50% midroll and a postroll in chrome mobile browser. 

**Smartphone (please complete the following information if relevant):**
 - Device: oneplus 6t and others
 - OS: android
 - Browser chrome 
 - Version 83.0.4103.106

**Comment by Addvilz** [comment]
Hello!

Apologies, but this ticket has been closed because there is no actionable way to identify what the actual issue is.

The initial ticket description fails to provide details required to identify the problem, such as error output, request logs, environment and browser details, and other details that could aid and allow in identifying the problem you are facing.

Before submitting a new ticket, please make sure that the problem you are facing is related to this software and is not a result of a misconfiguration or third party code - including your usage of this software. 

As a general rule, we are unable to help with user-specific implementation details, and we are not able to debug user implementations, such as websites, plugins, scripts, etc..

**You are required to take the minimum steps necessary to identify the issue, such as debugging the software, your specific configuration, the requests made, the responses returned by any external services.**

You are required to submit enough details about the problem so that we would be able to reproduce and verify the problem.

Make sure to fill out any issue templates as provided by the issue tracker when such templates are present.

This is an automatic response. Please, do not reopen or re-create this ticket without addressing the requirements and problems outlined above.
