### ISSUE TITLE
MKV VueJs Error

### ISSUE THREAD

**Issue by thesmartrenovation** [fluid-player/fluid-player#501]
Hi, I'm creating an IPTV player on VueJS but I'm having trouble playing the MKVs.

The provider gives me a link like this: 

http://urlprovider:port/movie/user/pass/file.mkv

But when I play it the console shows this error:

```
fluidplayer.js?8faf:530 [Error] (204): [FP_ERROR] Timeout error. Failed to play video?
self.announceLocalError @ fluidplayer.js?8faf:530
eval @ fluidplayer.js?8faf:417
setTimeout (async)
playerNode.play @ fluidplayer.js?8faf:415
self.playPauseToggle @ fluidplayer.js?8faf:1540
initPlayFunction @ fluidplayer.js?8faf:2254
```

But that same link works in other applications such as VLC.

This is de code:

```
<template>
  <div class="fluid-component">
    <video ref="myVideoPlayer">
      <source :src="$route.params.url" data-fluid-hd title="1080p" type="video/mp4" />
    </video>
  </div>
</template>

<script>
import fluidPlayer from "fluid-player";

export default {
  name: "FluidPlayer",
  props: {},
  data() {
    return {
      player: null
    };
  },
  mounted() {
    console.log(this.$route.params.url)
    this.player = fluidPlayer(this.$refs.myVideoPlayer);

  },
  destroyed() {
    if (!this.player) {
      return;
    }

    this.player.destroy();
  }
};
</script>

<style scoped>
@import "~fluid-player/src/css/fluidplayer.css";

div.fluid-component,
div.fluid-component > video {
  width: 100%;
  height: 100%;
}
</style>
```
I would really appreciate any help, it's the only thing I need to finish the software.

**Comment by Addvilz** [comment]
.MKV is simply a container format - it does not specify what kind of video and audio content is actually in the the file. Browsers do not support the same file and audio formats VLC does. That might be one problem. Without a concrete file example there is very little I can help you with.

Another issue might be network issues or missing permissions, or something. Did you check the error console? Network tab? Any errors there?

As far as the error goes - it does not mean what you assume it does - it means playback was not able to start within given amount of time, but it is possible that it is still buffering and will start playing later.

**Comment by thesmartrenovation** [comment]
> .MKV is simply a container format - it does not specify what kind of video and audio content is actually in the the file. Browsers do not support the same file and audio formats VLC does. That might be one problem. Without a concrete file example there is very little I can help you with.
> 
> Another issue might be network issues or missing permissions, or something. Did you check the error console? Network tab? Any errors there?
> 
> As far as the error goes - it does not mean what you assume it does - it means playback was not able to start within given amount of time, but it is possible that it is still buffering and will start playing later.

Hello, thank you for your response, the link to the video with the problem is this: http://163.172.20.176:8000/movie/IioWSeBLjB/Siv2YalyfE/108459.mkv

**Comment by Addvilz** [comment]
Sorry, I can not load given URL.

**Comment by thesmartrenovation** [comment]
> Sorry, I can not load given URL.

Please try again with this:
http://163.172.20.176:8000/movie/FVGFP7QFp8/sUys6bjZt2/108459.mkv

**Comment by Addvilz** [comment]
Your video is encoded using HEVC/H265 with AC-3 audio. Current HEVC support is documented here https://caniuse.com/#feat=hevc

You will not be able to play this video using FluidPlayer since the codec you are using is not supported by nearly any browser save for Safari. This is not a limitation of Fluid Player itself - the format you are using is simply not supported by majority of web browsers. The container file (aka .mkv) is fine - the problem is what the container contains.

The audio is even more exotic - DolbyDigital AC-3 - to the best of my knowledge, there are NO web browsers supporting this audio codec natively.

Realistically, you will need to transcode your video files to something much more widely supported, ex. MP4 (H264) with AAC audio.

To give you an example, our demo videos on our website are all also mkv containers, but what they contain is completely different:

What you have:

    Codec: MPEG-H Part2/HEVC (H.265) (hevc)
    Codec: A52 Audio (aka AC3) (a52)

What we have in our demo videos, as an example:

    Codec: H264 - MPEG-4 AVC (part 10) (avc1)
    Codec: MPEG AAC Audio (mp4a)
