### ISSUE TITLE
Fluid Player not playing Vast ads

### ISSUE THREAD

**Issue by SinglesCave** [fluid-player/fluid-player#516]
Fluid Player not playing Vast ads from adsterra.

Using this script here: ( may be the issue)

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.css" type="text/css"/>
<script src="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js"></script>
<video id='my-video'>
<source src='http://barrettelectronics.com/videos/videoplayback.mp4' type='video/mp4'/>
</video>

<script type="text/javascript">
'my-video',
    {
        layoutControls: {
            primaryColor:           false,
            playButtonShowing:      true,
            playPauseAnimation:     true,
            fillToContainer:        false,
            autoPlay:               true,
            mute:                   false,
            keyboardControl:        true,
            layout:                 'default',
            allowDownload:          false,
            playbackRateEnabled:    true,
            allowTheatre:           false,
            controlBar: {
                autoHide:           true,
                autoHideTimeout:    3,
                animated:           true
            },
            timelinePreview:        {},
            htmlOnPauseBlock: {
                html:               null,
                height:             null,
                width:              null
            },
            playerInitCallback:     (function() {})
        },
        vastOptions: {
            adList: [
                {
                    roll: 'preRoll',
                    vastTag: 'https://www.videosprofitnetwork.com/watch.xml?key=40e0cde8d71802bf0ca8a444f4e3e3a8',
                    skipButtonCaption: 'Espere [seconds] segundo(s)',
                    vastTimeout:                5000

                }
            ]
        }
    }
)
</script>

**Comment by Addvilz** [comment]
Hello,

sorry but this issue has been closed because there is **no actionable way to identify what the actual issue is**. The initial task description fails to provide details required to identify an issue, such as error output, request logs, environment and browser details, and other such details that could allow to identify the issue you are facing.

"Something does not work for some reason" is not an acceptable issue report. Before creating a issue report you must make sure the issue is with the software in question and not any 3rd party code. 

**You need to make at least the very minimum steps to identify the issue, such as debug your configuration, the requests made, the responses returned by any external services.** 

Make sure to fill out any issue templates as provided by the issue tracker (if such templates are present).

This is an automatic response. Please, do not reopen this issue without addressing the issues outlined above.
