### ISSUE TITLE
Error 101 & Error 900 

### ISSUE THREAD

**Issue by aaeq16** [fluid-player/fluid-player#527]
I'm having the next issue:

fluidplayer.min.js:8 [Error] (101): Failed to load Vast
t.announceLocalError @ fluidplayer.min.js:8
fluidplayer.min.js:8 [Error] (900): Failed to load Vast
t.announceLocalError @ fluidplayer.min.js:8
4fluidplayer.min.js:8 [Error] (101): Failed to load Vast
t.announceLocalError @ fluidplayer.min.js:8

**Comment by Addvilz** [comment]
Hello,

sorry but this issue has been closed because there is **no actionable way to identify what the actual issue is**. The initial task description fails to provide details required to identify an issue, such as error output, request logs, environment and browser details, and other such details that could allow to identify the issue you are facing.

"Something does not work for some reason" is not an acceptable issue report. Before creating a issue report you must make sure the issue is with the software in question and not any 3rd party code. 

**You need to make at least the very minimum steps to identify the issue, such as debug your configuration, the requests made, the responses returned by any external services.** 

Make sure to fill out any issue templates as provided by the issue tracker (if such templates are present).

This is an automatic response. Please, do not reopen this issue without addressing the issues outlined above.
