### ISSUE TITLE
the player wont play. it only show pic. 

### ISSUE THREAD

**Issue by nochill99** [fluid-player/fluid-player#528]
the player wont play. it only show pic. 

<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<video id="video-id"><source src="https://video.wixstatic.com/video/3a796d_57b8405912f84e4e8c972e587bb7368a/720p/mp4/file.mp4" type="video/mp4" />
<script>
    var myFP = fluidPlayer(
        'video-id',	{
	"layoutControls": {
		"controlBar": {
			"autoHideTimeout": 3,
			"animated": true,
			"autoHide": true
		},
		"logo": {
			"imageUrl": null,
			"position": "top left",
			"clickUrl": null,
			"opacity": 1
		},
		"htmlOnPauseBlock": {
			"html": "",
			"height": "",
			"width": ""
		},
		"autoPlay": true,
		"mute": true,
		"allowTheatre": false,
		"playPauseAnimation": true,
		"playbackRateEnabled": false,
		"allowDownload": true,
		"playButtonShowing": true,
		"fillToContainer": false,
		"posterImage": ""
	},
	"vastOptions": {
		"adList": [
			{
				"roll": "preRoll",
				"vastTag": "https://syndication.realsrv.com/splash.php?idzone=4001188",
				"adText": ""
			},
			{
				"roll": "midRoll",
				"vastTag": "https://syndication.realsrv.com/splash.php?idzone=4001146",
				"adText": ""
			},
			{
				"roll": "postRoll",
				"vastTag": "https://www.videosprofitnetwork.com/watch.xml?key=6859171cea38fbbd659999d76fb76ffc",
				"adText": ""
			},
			{
				"roll": "onPauseRoll",
				"vastTag": "https://syndication.realsrv.com/splash.php?idzone=4001146",
				"adText": ""
			}
		],
		"adCTAText": false,
		"adCTATextPosition": ""
	}
}
</script>

**Comment by Addvilz** [comment]
Hello,

sorry but this issue has been closed because there is **no actionable way to identify what the actual issue is**. The initial task description fails to provide details required to identify an issue, such as error output, request logs, environment and browser details, and other such details that could allow to identify the issue you are facing.

"Something does not work for some reason" is not an acceptable issue report. Before creating a issue report you must make sure the issue is with the software in question and not any 3rd party code. 

**You need to make at least the very minimum steps to identify the issue, such as debug your configuration, the requests made, the responses returned by any external services.** 

Make sure to fill out any issue templates as provided by the issue tracker (if such templates are present).

This is an automatic response. Please, do not reopen this issue without addressing the issues outlined above.

**Comment by Addvilz** [comment]
Please, do some debugging before submitting a bug. 101 and 909 errors usually occur when VAST is either invalid or can not be loaded due to network errors, adblockers etc. Check the network tab of the browser, validate VAST responses, do some debugging.

Please, do not submit more tickets before making sure there is an actual bug in the player code.
