### ISSUE TITLE
About error only displayed when using fluidplayer

### ISSUE THREAD

**Issue by mozgbrasil** [fluid-player/fluid-player#532]
++

Good afternoon my friends

To all who can help in advance thank you

++

The following is a vast URL

    https://bs.serving-sys.com/Serving/adServer.bs?c=23&cn=display&pli=1075789602&gdpr=${GDPR}&gdpr_consent=${GDPR_CONSENT_68}&ord={timestamp]

++

As in the fluidplayer project there is no testing environment

The following is an example of the fluidplayer configured with a vast URL

    https://codepen.io/rafael-roberto/pen/MWeKqBW

Where to start the video, is to apply js error

    TypeError not captured: null 'appendChild' property cannot be read

In case of occurrence only displayed when using the fluidplayer

++

This player allows you to perform the test

    https://www.openplayerjs.com/

When entering the vast URL we see that it works as expected

++

This player allows you to perform the test

    https://flowplayer.com/developers/tools/ad-tester

When entering the vast URL we see that it works as expected

++

This player allows you to perform the test

    https://adplayer.pro/developer/vast_inspector

When entering the vast URL we see that it works as expected

++

This service allows you to perform the test

    https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector

When entering the vast URL we see that it works as expected

++

This service allows you to perform the test

    http://test-a-tag.com/#

When entering the vast URL we see that it works as expected

++

This service allows you to perform the test

    https://demo.brid.tv/inspector

When entering the vast URL we see that it works as expected

++

**Comment by Addvilz** [comment]
> `TypeError not captured: null 'appendChild' property cannot be read`

This can mean anything. Please provide full stack trace, I am not able to reproduce using your reproduce code (CORS errors)

**Comment by Addvilz** [comment]
Hello!

Apologies, but this ticket has been closed because there is no actionable way to identify what the actual issue is.

The initial ticket description fails to provide details required to identify the problem, such as error output, request logs, environment and browser details, and other details that could aid and allow in identifying the problem you are facing.

Before submitting a new ticket, please make sure that the problem you are facing is related to this software and is not a result of a misconfiguration or third party code - including your usage of this software. 

As a general rule, we are unable to help with user-specific implementation details, and we are not able to debug user implementations, such as websites, plugins, scripts, etc..

**You are required to take the minimum steps necessary to identify the issue, such as debugging the software, your specific configuration, the requests made, the responses returned by any external services.**

You are required to submit enough details about the problem so that we would be able to reproduce and verify the problem.

Make sure to fill out any issue templates as provided by the issue tracker when such templates are present.

This is an automatic response. Please, do not reopen or re-create this ticket without addressing the requirements and problems outlined above.
