### ISSUE TITLE
problem in subtitles defualt

### ISSUE THREAD

**Issue by mdoulabi** [fluid-player/fluid-player#547]
hi 
i have 2 subtitles vtt and select a subtitle for default ,but on player is off selected . what problem?
my code :
<video id="my-video" controls>
    <source src="video.mp4" type="video/mp4"/>
    <track label="English" kind="metadata" srclang="en" src="/subtitles/english.vtt" default>
    <track label="Deutsch" kind="metadata" srclang="de" src="/subtitles/deutsch.vtt">
</video>

<script type="application/javascript">
fluidPlayer(
    'my-video',
    {
        layoutControls: {
            subtitlesEnabled: true
        }
    }
);
</script>

**Comment by Addvilz** [comment]
Hello!

Apologies, but this ticket has been closed because there is no actionable way to identify what the actual issue is.

The initial ticket description fails to provide details required to identify the problem, such as error output, request logs, environment and browser details, and other details that could aid and allow in identifying the problem you are facing.

Before submitting a new ticket, please make sure that the problem you are facing is related to this software and is not a result of a misconfiguration or third party code - including your usage of this software. 

As a general rule, we are unable to help with user-specific implementation details, and we are not able to debug user implementations, such as websites, plugins, scripts, etc..

**You are required to take the minimum steps necessary to identify the issue, such as debugging the software, your specific configuration, the requests made, the responses returned by any external services.**

You are required to submit enough details about the problem so that we would be able to reproduce and verify the problem.

Make sure to fill out any issue templates as provided by the issue tracker when such templates are present.

This is an automatic response. Please, do not reopen or re-create this ticket without addressing the requirements and problems outlined above.

**Comment by SalimF** [comment]
I have same issue the subtitle are always off 

<video id="example-player" style="width: 700px; height: 360px;"> <source src="https://mysite/myvideo.mkv" type="video/mp4"/>
<track label="Arabic" kind="metadata" srclang="ar" src="https://mysite/myvideo.vtt" default>
</video> 

<script src="//cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
 <script>
 // fluidPlayer method is global when CDN distribution is used.
fluidPlayer(
    'example-player',
    {
        layoutControls: {
            subtitlesEnabled: true
        }
    }
);
</script>

<link rel="stylesheet" href="https://mysite/wp-content/themes/mytheme/fluidplayer.css" type="text/css"/>

![image](https://user-images.githubusercontent.com/16048674/184540111-6ce6b192-c4dd-4db3-a24f-9b9bb7a15166.png)
