### ISSUE TITLE
Post-roll ended event

### ISSUE THREAD

**Issue by Barahten** [fluid-player/fluid-player#557]
How to catch the event of the end of playing a post-roll?

`player.on ('ended', function () {console.log ('Video is now ended');});`
сalled twice - first before showing the post-roll, then after the end of the post-roll
[https://docs.fluidplayer.com/docs/api/events/#ended](https://docs.fluidplayer.com/docs/api/events/#ended)

**Comment by adamstruve** [comment]
I've noticed this issue as well.
`on('ended', function(){}) ` is called when a VAST pre/post roll finishes or if you click skip. Most of the time if we are using this function it's because we want to do something when the main video ends and not when the preroll ends. I can see how it would be useful to trigger it when the preroll ends too.

**Comment by leroybm** [comment]
Created a ticket for this issue since it's still happening

**Comment by leroybm** [comment]
@Barahten @adamstruve The events were not different for ads and the main video since they are just passing along the HTML5 video player event. As to not mess with the event handlers, I've added additional information to the callback attributes, so you can programatically check what is the source of the event. 

You can check the docs here: https://docs.fluidplayer.com/docs/api/events/#additional-information

Please let me know if this fixes this issue

**Comment by sergiomcsousa** [comment]
No answer from the reporter. Closing the ticket.
