### ISSUE TITLE
fluidPlayer function syntax

### ISSUE THREAD

**Issue by benjabcn** [fluid-player/fluid-player#61]
Is there any particular reason with the "vastTag" parameter is set as a separate parameter in the function? When using the player without VAST, it makes the function call slightly awkward as it forces you to set an empty parameter before to have the options array.

Why not having it as one more option in the array?

Also, since there are a few options that are specific to VAST, why not having them as a sub-array to group them together?

Just some syntax suggestions...

**Comment by Danny15** [comment]
Hi @benjabcn, thank you for your comments. There is no particular reason with the "vastTag" parameter set as a separate parameter in the function. We will look to discuss it when considering future improvements to improve syntax but we cannot fully remove the vast tag as a second parameter, because it will break existing Fluid Player setups. so it may have to be supported both ways.

**Comment by golikov** [comment]
The vastTag has been reimplemented as adList object inside options, so there is no need to indicate it as second parameter.
