### ISSUE TITLE
Fullscreen bug?

### ISSUE THREAD

**Issue by benjabcn** [fluid-player/fluid-player#62]
When going fullscreen on this page : https://fuckler.com/video/62663/skinny-brunette-gets-hardcore-fun-during-xxx-massage/

I can only see half of the video, the functionality seems to be broken. And when escaping, the control remain as if I was still in fullscreen.

Under Linux. Chrome v60

**Comment by Danny15** [comment]
Hi @benjabcn, thank you for raising this issue with us. 

For the first part where the full screen only displays half the video, this looks to be specific to this site and due to some custom CSS added by the user, specifically with .fluid_video_wrapper{height:0;padding-bottom:56.25%;}. This seems to be affecting Chrome as on Firefox 57 the full screen video displays correctly on this site.

The issue with the controls remaining as if in full screen after escaping does look to be a bug with latest Fluid Player. We are now reviewing this behavior on different browsers & devices and will hope to have improvements for this in one of our future releases.

**Comment by kristijanexads** [comment]
@benjabcn fullscreen issue is now sorted and available in Fluid Player version [v1.2.0](https://github.com/fluid-player/fluid-player/releases/tag/v1.2.0)

**Comment by tudy000** [comment]
This is probably late but the problem persists on chrome PC and even on Waterfox,mainly on porn sites,i mean what is the deal with this fullscreen problem? https://www.heavy-r.com/video/319147/Squirting_BBW/

**Comment by ShpendBerisha** [comment]
you can take a look here https://github.com/fluid-player/fluid-player/issues/239
two css lines can fix your problem.

**Comment by jacanidjar** [comment]
yes , problem continue ='[
