### ISSUE TITLE
No way to make the "Logo" appear always ?

### ISSUE THREAD

**Issue by chajo1997** [fluid-player/fluid-player#640]
While using the logo layout option I can't seem to make the logo appear always, intead it shows only when controls are shown which I don't want.
Is there a way to make the logo appear always ? 
The only option I found was hideWithControls and no matter what value I give it, the logo still shows only when I hover the video player.

**Comment by Mersal-Mohamed** [comment]
same here

**Comment by ZentoDH** [comment]
Hi @chajo1997. I was able to recreate it, with in version 3.0.x and I’ve noticed that the bug was fixed in 3.1.0. So I would recommend updating. If that doesn’t fix it or you’re using a higher version, please share your config file and version that you’re using.
<img width="500" alt="Screenshot 2022-07-21 at 11 08 34" src="https://user-images.githubusercontent.com/28918877/180189552-288c5bbe-c46c-4be5-9c4b-4a8608b98878.png">
<img width="500" alt="Screenshot 2022-07-21 at 11 10 20" src="https://user-images.githubusercontent.com/28918877/180189606-774cd148-71ff-489b-a10f-dadb3bdc1c75.png">

**Comment by HariPriyaKuberSingh** [comment]
@chajo1997  - Can you please confirm if the comments by zento helped in resolving the issue

**Comment by HariPriyaKuberSingh** [comment]
Since there is no response from the reporter, we are closing the ticket. We can open it again if there is any response. Thanks
