### ISSUE TITLE
The player stops displaying the video after a period of time and displays the advertisement only

### ISSUE THREAD

**Issue by saifassizoz** [fluid-player/fluid-player#696]
**Describe the bug**
After about a few hours, the player stops showing videos and only displays ads. I'm not a programmer but I followed the youtube instructions to turn on fluid player in blogger but the player always works on the first day and then stops showing videos
Please help me find a solution as soon as possible. I have tried v3, v2, 3.0.0 and the problem has not changed

**Comment by leroybm** [comment]
Hello @saifassizoz, what do you mean by a few hours? Is the player open playing a long video? Do you see any errors in your developer tools console?

**Comment by saifassizoz** [comment]
> Hello @saifassizoz, what do you mean by a few hours? Is the player open playing a long video? Do you see any errors in your developer tools console?

My friend, I'm just trying to play my videos from google drive and add vast ads from adsterra, but the player stops playing the video after one day or less, does fluidplayer play the video only once? Isn't it supposed to work permanently?

I am not a programmer, but I own a website to display videos, and I used the doodstream platform, but I am not comfortable with it
I just want to use vast ads on my site, and I resorted to using google drive to upload videos and fluid player to run them and take advantage of the ads feature
The problem that I am posing is that I try the video after setting up the player, and I find that it works, but the visitors on my site complain that the videos do not work, so I return to verify that to find that the video player displays the advertisement only and then stops

Do you have advice for me?

**Comment by saifassizoz** [comment]
Some people have told me I shouldn't use videos longer than 10 minutes
Others told me that I should not use google drive with fluid player, but I do not know which platform to use to ensure that the videos will work with ads forever!!

**Comment by leroybm** [comment]
You can make sure that your video works using it without Fluid Player, using a tag like this one without Fluid Player.
```
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>
```
Hosting videos is outside of the domain of Fluid Player, so this is something that we can't help with. I believe the best action is looking for a CDN that can give you confidence that your video will be delivered to your visitors. Your current choice of hosting can be limiting the delivery of your content due to high bandwidth usage or some other policy.

**Comment by Aizmansor** [comment]
Dihantar daripada telefon saya-------- Mesej asal --------Daripada: Leroy Medeiros ***@***.***>Tarikh: Isn, 21 Nov 2022, 8:11 PTGKepada: fluid-player/fluid-player ***@***.***>Sk: Subscribed ***@***.***>Tajuk: Re: [fluid-player/fluid-player] The player stops displaying the video after a period of time and displays the advertisement only (Issue #696)
You can make sure that your video works using it without Fluid Player, using a tag like this one without Fluid Player.
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>

Hosting videos is outside of the domain of Fluid Player, so this is something that we can't help with. I believe the best action is looking for a CDN that can give you confidence that your video will be delivered to your visitors. Your current choice of hosting can be limiting the delivery of your content due to high bandwidth usage or some other policy.

**Comment by leroybm** [comment]
@saifassizoz Personally I don't know any specific platforms, this will depend on your use case, costs, performance, etc... Closing the ticket since it's not related with FP.
