### ISSUE TITLE
Problems with the video preloading

### ISSUE THREAD

**Issue by traffictitan** [fluid-player/fluid-player#724]
Videos don't preload on either desktop or mobile.  I'm using HLS.  The correct behavior would be that about 30 seconds of video is buffered before the user clicks the play button.  It's critical for google correctly indexing video pages.  Google will otherwise select a banner or whatnot if no videos are playing.

Setup:

<script>
    var myFP = fluidPlayer(
        'video-id',	{
			"modules": {
				configureHls: (options) => ({
					maxMaxBufferLength: 30,
					startLevel: 4
				})
					},
			"layoutControls": {
				"controlBar": {
					"autoHideTimeout": 3,
					"animated": true,
					"autoHide": true
				},
				"htmlOnPauseBlock": {
					"html": null,
					"height": null,
					"width": null
				},
				"timelinePreview": {
					"file": "{/literal}/stp/vtt.php?v={$file.cache_id}{literal}",
                	"type": "VTT"
				},
				"autoPlay": false,
				"mute": false,
				"allowTheatre": true,
				"playPauseAnimation": true,
				"playbackRateEnabled": true,
				"allowDownload": false,
				"preload": "auto",
				"playButtonShowing": true,
				"fillToContainer": true,
			}
		});
</script>

**Comment by leroybm** [comment]
Hi @traffictitan, using HLS the video will be preloaded by default, this is due to the behaviour of `hls.js`. As for the `preload` attribute on video or Fluid Player, it will only work with native browser media (Like mp4 or webm).

The property to enable preload is `autoStartLoad` for `hls.js`, with your config it would look something like this (If set to `false`, Fluid Player doesn't handle the stream very well so I advice leaving it as `true`):
```javascript
configureHls: (options) => ({
    maxMaxBufferLength: 30,
    startLevel: 4,
    autoStartLoad: true
})
```

You can check that the video is being preloaded by checking the network tab in dev tools. If you change `maxMaxBufferLength` you will see the amount of preload in the network tab change too.

As for Google indexing, I've checked their public docs and didn't find anything related to video preload, can you share your resoruces? I did find some info about setting up [structured data](https://developers.google.com/search/docs/appearance/structured-data/video) with a valid fetchable stream link, maybe you can check that out.

**Comment by traffictitan** [comment]
Hmm i swear i checked it with network and it wasn't working.  Seems to work now.  It should show how much is preloaded in the timeline bar and show the video duration before the video play button is clicked.  Similar to how xvideos.com works.  Also is there an option to show player control on mobile before clicking the video?

**Comment by leroybm** [comment]
I've checked with the suggested configuration above and the progress bar shows that it's loaded even before playing. Can you share your configurations? Maybe I'm setting it up wrong.
![image](https://github.com/fluid-player/fluid-player/assets/8548779/6063041b-ea7d-4163-b833-e94321f5f1fe)

As for the control bar options, you can check the available options here, https://docs.fluidplayer.com/docs/configuration/layout/#controlbar. 

In regards of the google indexing, have you taken a look at the structured data info?

**Comment by leroybm** [comment]
@traffictitan is this still an issue?

**Comment by sergiomcsousa** [comment]
@traffictitan is this still and issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
