### ISSUE TITLE
.m3u8 files freezing in Android browser (Chrome, Brave)

### ISSUE THREAD

**Issue by Fathomed** [fluid-player/fluid-player#773]
My Fluid Player setup is working well except in one particular use case:
When playing .m3u8 files on any Android browser, the picture freezes with the first few seconds while the audio keeps playing.
Video are served from Cloudflare Stream. 
I've tested with other open source players with no issues (except they don't provide Vast support 😀). I'd be grateful for any help.
Here's my implementation:
`<video id="hls-video" style="width: 100%; height: auto;" preload="false">
    <source src="https://customer-*********cloudflarestream.com/***********/manifest/video.m3u8" type="application/x-mpegURL" />
  </video>`
`<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script> <script async> fluidPlayer('hls-video', { layoutControls: { primaryColor: "#1d395a", // Customize the primary color preload: "false", // Default 'auto' fillToContainer: true, autoPlay: false, // Set to true if you want to auto play the video playbackRateEnabled: true, allowTheatre: false, controlBar: { autoHide: true, autoHideTimeout: 3, animated: true, posterImage: 'customer-***********.cloudflarestream.com/*************/thumbnails/thumbnail.jpg?time=6m16s', posterImageSize: 'cover' // Default `contain` }, }, vastOptions: { vastTimeout: 5000, // Milliseconds to wait for VAST to load adList: [ { roll: "preRoll", // preRoll, midRoll, postRoll vastTag: "https://servedby.revive-adserver.net/fc.php?script=apVideo:vast2&zoneid=17205&skipoffset=10", }, ], }, }); </script>`

**Comment by mcorbelli** [comment]
Any update?

**Comment by sergiomcsousa** [comment]
[](https://github.com/fluid-player/fluid-player/issues/770) I think this could be the same issue. I have opened an internal ticket mentioning both of these cases.

**Comment by sergiomcsousa** [comment]
@Fathomed The fix for this issue is available on the latest version. Can you please confirm and let me know if we can close this ticket? Thank you!

**Comment by ZentoDH** [comment]
Hi @Fathomed,

To provide some context, I tested this on a standard `<video>` tag and noticed the issue still occurred. This is likely because Chrome on Android, for example, supports HLS natively, but the implementation isn't great. In Fluid Player, we check for native HLS support, and if it's present, we skip loading HLS.js, instead relying on the browser's native HLS handling.

We found that HLS.js works a bit more consistently, not perfect, but better. The problem with native HLS is that the browser has all the control over stuff like `maxMaxBufferLength`, you can't change it. With HLS.js you have a lot more control over stuff like that. The more I work with HLS, I notice support is quite bad over the board. 

I've added a flag that allows you to override native HLS support when available, and instead force the use of HLS.js. This way you have more control.

```html
<script>
fluidPlayer(
    'hls-video',
    {
        hls: {
            overrideNative: true
        }
    }
);
</script>
```

**NOTE**: if you're using the `https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js`, it takes 24h for the cache to update so the change might not be there if you test it today. You'll have to use `https://cdn.fluidplayer.com/3.35.0/fluidplayer.min.js` if you want to use it today.

**Comment by ZentoDH** [comment]
It's been 2 weeks since our response with no answer, hence closing this issue. We assume this fixed the problem, if not you can always create a new ticket. 

Thanks for contributing and/or using Fluid Player!
