### ISSUE TITLE
Seeking doesn't work on mobile devices properly consistently

### ISSUE THREAD

**Issue by traffictitan** [fluid-player/fluid-player#792]
Fluidplayer has recently developed an issue where if you seek to a different time in a video the picture freezes but the sound continues playing.  Seems to only happen on mobile devices.  I'm using a samsung phone with chrome browser.  Seems to work on desktop and firefox and other browsers.  Issue as far as I can tell is only chrome on mobile.

Example of error.  I start playing video.  I seek ahead to 5:00 in the video by clicking the timeline.  Video continues to play but picture is frozen.  Sounds still keeps playing

Multiple users have reported the same bug.

**Comment by sergiomcsousa** [comment]
This issue is mentioned #https://github.com/fluid-player/fluid-player/issues/770, I have created an internal ticket and linked this.

**Comment by ZentoDH** [comment]
Hi @traffictitan,

This seems to be a problem with the native implementation of HLS on certain browsers on mobile.

To provide some context, I tested this on a standard `<video>` tag and noticed the issue still occurred. This is likely because Chrome on Android, for example, supports HLS natively, but the implementation isn't great. In Fluid Player, we check for native HLS support, and if it's present, we skip loading HLS.js, instead relying on the browser's native HLS handling.

We found that HLS.js works a bit more consistently, not perfect, but better. The problem with native HLS is that the browser has all the control over stuff like `maxMaxBufferLength`, you can't change it. With HLS.js you have a lot more control over stuff like that. The more I work with HLS, I notice support is quite bad over the board. 

I've added a flag that allows you to override native HLS support when available, and instead force the use of HLS.js. This way you have more control.

```html
<script>
fluidPlayer(
    'hls-video',
    {
        hls: {
            overrideNative: true
        }
    }
);
</script>
```

**NOTE**: if you're using the `https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js`, it takes 24h for the cache to update so the change might not be there if you test it today. You'll have to use `https://cdn.fluidplayer.com/3.35.0/fluidplayer.min.js` if you want to use it today.

**Comment by ZentoDH** [comment]
It's been two weeks with no response, hence closing the ticket. We assume this fixed the problem, if not you can open a new ticket.

Thanks for contributing and/or using fluid player!
