### ISSUE TITLE
Browser errors were logged to the console

### ISSUE THREAD

**Issue by macthebot1** [fluid-player/fluid-player#798]
When the FluidPlayer player is active on my page, this error appears in PageSpeed

ERRO MP4
(Note: the mp4 loads normally when I press play)

![Captura de tela 2024-02-22 111210 copy](https://github.com/fluid-player/fluid-player/assets/160875288/f4c3ab7f-e995-4d36-ad87-02043d6649d9)

**I noticed that this problem only occurs when vast is active**

If I remove the error it disappears, could you check the cause of this problem, please.

Thanks

**Comment by ZentoDH** [comment]
Hi @macthebot1, we're looking into this issue atm.
The reason why the error is thrown is because the browser can't find the video you provided. It's a 404, or maybe it doesn't have read access to the video. Now, what would you want to change exactly? Do you want us to catch this error and throw a custom error in the console instead?

**Comment by sergiomcsousa** [comment]
@macthebot1 Does the issue still persist? I can see that Zento gave feedback a month ago. If there is no issue can you please close the ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing this ticket due to lack of feedback/this one was user error
