### ISSUE TITLE
Fluidplayer fails to play VAST creatives with wrappers

### ISSUE THREAD

**Issue by eduardoguette** [fluid-player/fluid-player#852]
**Describe the bug**
Fluidplayer is unable to play VAST creatives that contain a wrapper. When attempting to load a VAST creative with a wrapper, the player fails to process the response, and the video does not display or play.

**To Reproduce**
1. Go to https://jsfiddle.net/vgn51pcj/2/ 
3. Open Developer Tools 
2. Click on "Play video"
4. See error Player not display creative

**Expected behavior**
The player should be able to handle and play VAST creatives with a wrapper, as it does with simple VAST creatives. When receiving a VAST with a wrapper, Fluidplayer is expected to correctly cascade through the requests until reaching the video and then play it.

**Screenshots or Links**
 
https://jsfiddle.net/rezb8knq/1/
<img width="1087" alt="image" src="https://github.com/user-attachments/assets/b1d18e28-9b05-4f62-a013-28dfd220da85">

**Affected version**
Lastest version

**Comment by soundrussian** [comment]
@brunopick This issue can also be reproduced in vod_vast_wrapper.html example of the repo.

It's kinda serious, because many adnetworks use Wrapper elements in their ads.

I've added a possible fix in this PR https://github.com/fluid-player/fluid-player/pull/853, feel free to reject it and fix as seems fit to you. Can't say I have a deep understading of what's going on in VAST handling, but I've just noticed an astray code block in the latest release and moved it where it seemed to fit 😄

**Comment by Barti-sys** [comment]
Hello, I can confirm that in the latest version of FluidPlayer, the roll: 'onPauseRoll' setting is not functioning correctly, as it fails to display the banner ad.

**Comment by sergiomcsousa** [comment]
@ZentoDH can you please check this issue here? @soundrussian created a PR. Can you take a look at it?

**Comment by sergiomcsousa** [comment]
@soundrussian actually a fix was released today. It can take up to 24h for the cache.

**Comment by sergiomcsousa** [comment]
@eduardoguette can this ticket be closed? Thank you!
